#
#      ______         _                   
#      |  ___|       | |                  
#      | |_ __ _  ___| |_ ___  _ __ _   _ 
#      |  _/ _` |/ __| __/ _ \| '__| | | |
#      | || (_| | (__| || (_) | |  | |_| |
#      \_| \__,_|\___|\__\___/|_|   \__, |
#                                    __/ |
#                                   |___/ 
#
#  Factory - A modded experience brought into Spigot
#    Developed by Santio71
#

#
# WEB
#  This configuration section is used to host a mini
#  webserver used to send a generated resource pack to
#  the user for the custom items & blocks made with Factory
#
web:
  ip: localhost # What IP to run on
  port: 3000 # What port to bind on (should be different from your server port)